#!/bin/bash

### BEGIN INIT INFO
# Provides:          etcd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO


. /lib/lsb/init-functions

prog="etcd"
ETCD_BIN="/usr/local/bin/etcd"
ETCD_LOGFILE="/var/log/etcd.log"
ETCD_PIDFILE="/var/run/$prog.pid"
ETCD_EXEC="$ETCD_BIN"
ETCD_ARGS="-addr=0.0.0.0:4001"

if [[ ! -e $ETCD_BIN ]]; then
  echo "$prog binary not found."
  exit 5
fi

if [[ ! -e $ETCD_LOGFILE ]]; then
  touch $ETCD_LOGFILE
fi

if [[ ! -e $ETCD_PIDFILE ]]; then
  touch $ETCD_PIDFILE
fi


start() {

  echo -n $"Starting $prog: "
  if start-stop-daemon --start --quiet --pidfile $ETCD_PIDFILE -b -m --exec $ETCD_EXEC -- $ETCD_ARGS >> $ETCD_LOGFILE; then
    log_end_msg 0
  else
    log_end_msg 1
  fi
}

stop() {
  echo -n $"Stopping $prog: "
  start-stop-daemon --stop --quiet --oknodo --pidfile "$ETCD_PIDFILE"
}

status() {
  echo -n "Status $prog: "
  status_of_proc -p $pid_file "" "$prog"
}


case $1 in
  start)
    start
    ;;

  stop)
    stop
    ;;

  restart)
    stop
    start
    ;;

  status)
    status
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|status}"
    RETVAL=1
    ;;
esac

exit $RETVAL
